### ISSUE TITLE
Make template.css

### ISSUE THREAD

**Issue by sharonvopzeeland** [MelvinIdema/blok-tech-team#29]
Hierin komt de algemene styling. :root, font-family etc

**Comment by MelvinIdema** [comment]
Goed idee!

**Comment by sharonvopzeeland** [comment]
Gulp runned niet? 😶

![Schermafbeelding 2022-03-26 om 10 09 52 AM](https://user-images.githubusercontent.com/94179710/160232790-83209d29-ebc2-42eb-8f93-cecf15ceb4bd.png)

**Comment by MelvinIdema** [comment]
NPM Install doen? Of is het al gelukt?

**Comment by sharonvopzeeland** [comment]
al gedaan maar werkt nog niet..

**Comment by sharonvopzeeland** [comment]
ah gefixd! sort of.. heb alle gulp installs handmatig moeten doen, een voor een dus.

**Comment by sharonvopzeeland** [comment]
Nu dit als ik naar localhost:3000 ga :/

![Schermafbeelding 2022-03-26 om 11 07 15 AM](https://user-images.githubusercontent.com/94179710/160234766-2f404bf0-8197-47f1-9cdc-61ec9cac94b3.png)

**Comment by MelvinIdema** [comment]
Rooie kringeltjes zijn vanwege ESLint die vind dat er een ; achter alles moet. 

Gekke errors. Lijkt erop dat niet alle NPM packages geïnstalleerd zijn. Misschien node_modules verwijderen en weer 'npm install' doen? :S

**Comment by MelvinIdema** [comment]
Oh wacht... in de package.json staan alle packages helemaal niet. Dus die worden niet geïnstalleerd. Denk dat er ergens iets fout is gegaan bij het mergen. Dus alles moet handmatig ge-npm-installed worden :/

**Comment by sharonvopzeeland** [comment]
Oke het is gelukt! Heb express en ejs ge-installerd en ik zie nu de header. Maar het linken lijkt niet gelukt te zijn, ik zie ook geen dist folder en dus ook nergens onze style.min.css
Ik heb nu de template.css in de src map gedaan, klopt dit? Te lezen uit de gulpfile.js haalt ie de css bestanden op hieruit nml en maakt ie een style.min.css in de public/dist folder maar dat gebeurd nu niet

**Comment by Bram-ter** [comment]
Hey, om nog even te terug te komen op deze issue. Ik heb er net even naar gekeken, en de reden waarom gulp geen dist map met een style.min.js maakte is omdat de file path die wij in onze gulpfile neer hadden gezet niet aanwezig is. 
`.src('./src/styles/*.css')` zo staat de map in onze gulpfile gespecificeerd, en hoe de structuur nu is staan de bestanden los in de src folder. Hoe willen wij dit aanpassen? deze files zo laten staan, of ze toch gewoon in een styles map zetten?

**Comment by sharonvopzeeland** [comment]
Ah ja dat klinkt logisch, we hebben wel een src map maar geen styles als ik het goed begrijp. Ik denk dat we een styles map kunnen aanmaken in de src map en die gelijk in de main pushen?
Dan kunnen de normale .css bestanden in de src map blijven en komt de style.min.css in de styles map die we dan zelf er in zetten.

**Comment by Bram-ter** [comment]
Ja precies, ik had het zelf in een andere branch waar ik in aan het werk was getest. En het toevoegen van een styles map in de src map waar je dan weer die losse css files inzet hoort het te doen. Dan maakt hij ook de dist folder aan met een style.min.css.

**Comment by sharonvopzeeland** [comment]
Ah wat top! Ja want we hadden natuurlijk de src map in plaats van de public map voor gulp gebruikt. Ik zal het zo even maken en pushen naar de main

**Comment by sharonvopzeeland** [comment]
Er is een dist map aangemaakt en het leek te werken maar gulp finished steeds gelijk.. Ik kan niet vinden hoe ik dit kan oplossen 🤨
![Schermafbeelding 2022-03-27 om 7 24 32 PM](https://user-images.githubusercontent.com/94179710/160293082-2e27b05c-b971-4048-9812-6c42ceb1c2a3.png)

**Comment by sharonvopzeeland** [comment]
Verder staat dit in de console 
![](file:///var/folders/bt/lj32bff52dj3mhskhcqf4lp40000gn/T/TemporaryItems/NSIRD_screencaptureui_TT6niu/Schermafbeelding%202022-03-27%20om%207.29.51%20PM.png)

**Comment by sharonvopzeeland** [comment]
OMG het is gelukt, weet niet precies hoe maar ik voegde `rel="stylesheet"` weer toe en toen deed ie het!
