### ISSUE TITLE
Setup Gulp 🖊

### ISSUE THREAD

**Issue by MelvinIdema** [MelvinIdema/blok-tech-team#4]
- [x] Initialize NPM 
- [x] Install Gulp
- [x] Setup Gulp
- [x] Have a full file structure for gulp to work

**Comment by MelvinIdema** [comment]
Ziet er goed uit! 

Zullen we in een `/src` mapje werken en het uitspugen in een `/public`?

**Comment by MelvinIdema** [comment]
` 
"dependencies": {
    "gulp": "^4.0.2",
    "gulp-autoprefixer": "^8.0.0",
    "gulp-clean-css": "^4.3.0",
    "gulp-concat": "^2.6.1",
    "gulp-nodemon": "^2.5.0",
    "gulp-uglify": "^3.0.2"
  },
`

Gulp is trouwens een devDependency 😉  Dus dit kan bij devDependencies.

**Comment by sharonvopzeeland** [comment]
> Ziet er goed uit!
> 
> Zullen we in een `/src` mapje werken en het uitspugen in een `/public`?
> 
> En wellicht alvast een test stukje opzetten. Kijken of alles werkt. Dus een css bestand en een JS bestand met wat simpele code erin en kijken of Gulp dat dan netjes uitspuugt. Als dat werkt kunnen we een pull-request doen!

Ja zeker! Laten we samen even snel naar de mappenstructuur kijken en deze toevoegen.

**Comment by MelvinIdema** [comment]
VGM is deze wel klaar toch?
