### ISSUE TITLE
Create appointment page 📅

### ISSUE THREAD

**Issue by danajamilla** [MelvinIdema/blok-tech-team#41]
- [x] Change appointment.ejs to confirm.ejs
- [x] Create appointment.ejs (appointment list)

**Comment by danajamilla** [comment]
Hi, weet iemand hoezo hij de button hier niet laat zien?

<img width="1439" alt="image" src="https://user-images.githubusercontent.com/94362031/160816806-33246a26-42b5-47f9-b96f-d53a332fda2d.png">

**Comment by sharonvopzeeland** [comment]
ik denk omdat ie eronder ligt, met `z-index="100"` oid kan je dit denk ik wel fixen!

**Comment by danajamilla** [comment]
> ik denk omdat ie eronder ligt, met `z-index="100"` oid kan je dit denk ik wel fixen! Nope dat heb je al.. uhm misschien een position absolute erop zetten?

Ja met absolute werkt het, thanks!

**Comment by MelvinIdema** [comment]
Ziet er top uit trouwens 👍🏼 Lekker bezigg
