### ISSUE TITLE
Create account page

### ISSUE THREAD

**Issue by danajamilla** [MelvinIdema/blok-tech-team#42]
- [x] make account page (Sharon)
- [ ] make avatar feature (Melvin)

**Comment by sharonvopzeeland** [comment]
Kan de account page gerenderd worden in User.js / UserController.js ?

**Comment by MelvinIdema** [comment]
Ja! Sterker nog, dat moet zelfs. 

Een feature bestaat uit minimaal 4 dingen: Create, Read, Update, Delete. In het geval van de User is Create dus registreren. Read is dus het profiel / account pagina. Update de settings / account pagina en delete een verwijder knop. Account is bij ons dus zowel het bekijken als wijzigen van een User.

**Comment by sharonvopzeeland** [comment]
Ah oke top, klinkt inderdaad ook logisch. Ik zal het vandaag erbij doen :)

**Comment by sharonvopzeeland** [comment]
Het lijkt erop dat je al een function heb voor account, wat houdt deze in? Als ik probeer `return res.render('account');` doe dan komt ie niet in de browser.

**Comment by sharonvopzeeland** [comment]
Alright, het is gelukt! Heb jouw code even uitgecommend want ik denk dat dit misschien nog nodig is om straks de data op te halen van de ingelogde user
![Schermafbeelding 2022-03-30 om 1 46 13 PM](https://user-images.githubusercontent.com/94179710/160827345-e08db18e-d203-44e9-9c00-eb422b60d49c.png)

**Comment by MelvinIdema** [comment]
Ja prima!
