### ISSUE TITLE
Copy styled buttons for Info & Cards page 💻

### ISSUE THREAD

**Issue by danajamilla** [MelvinIdema/blok-tech-team#43]
- [x] Copy button styles to info page
- [x] Copy button styles to cards page

**Comment by danajamilla** [comment]
@Martin803 @sharonvopzeeland De kruis button is iets aangepast, nu is hij mooi vierkant. Het enige wat aangepast hoeft te worden in de code is 
`width: 2.1em;`

**Comment by sharonvopzeeland** [comment]
Als we het morgen weer met z'n alle gaan mergen moet dat goed komen :) top!
