### ISSUE TITLE
Responsiveness

### ISSUE THREAD

**Issue by MelvinIdema** [MelvinIdema/blok-tech-team#49]
Volgens mij hadden we het hier van de week al over. Om gewoon de app vast te zetten op mobiele breedte zodat ie niet te breed wordt op desktop.

**Comment by MelvinIdema** [comment]
Dan ziet ie er zo uit op desktop:

![Schermafbeelding 2022-03-28 om 22 20 24](https://user-images.githubusercontent.com/2219074/160480324-17fd4dbd-43e2-498a-b9cd-debd6108f932.png)

**Comment by MelvinIdema** [comment]
En zo op mobiel:
![WhatsApp Image 2022-03-28 at 22 16 09](https://user-images.githubusercontent.com/2219074/160480379-8a73db4a-688c-4faa-87d9-9f1bff6c1d51.jpeg)

**Comment by sharonvopzeeland** [comment]
Ziet er heel goed uit zo! Beter dan die 700px denk ik, zo is ie perfect

**Comment by sharonvopzeeland** [comment]
BTW, footer met menu komt pas als je ingelogd hebt dus niet al op de eerste 2 pagina's ;) kunnen we zo weghalen!
