### ISSUE TITLE
Make a banner for Wiki

### ISSUE THREAD

**Issue by sharonvopzeeland** [MelvinIdema/blok-tech-team#50]
Make it look cool and interesting to read more

**Comment by sharonvopzeeland** [comment]
Eerste opzet, in onze stijl. Laat maar weten wat jullie ervan vinden en wijzig gerust in XD!
![banner-v1](https://user-images.githubusercontent.com/94179710/160487228-1c80d6db-c3f6-4e1d-8ddd-020a5e7b2b5a.png)

**Comment by sharonvopzeeland** [comment]
versie 2
![banner-v2](https://user-images.githubusercontent.com/94179710/160567159-c7ad6e35-2f85-4840-a60d-12cdd3ba21e0.png)

**Comment by MelvinIdema** [comment]
Nicee! Vind die "tags" erbij ook wel goed eigenlijk. Beetje een overzicht wat Pupples eigenlijk is

**Comment by danajamilla** [comment]
Cool! Ik zou voor het 2e ontwerp gaan en dan de slogan wat aanpassen. Bijvoorbeeld: "Vind jouw perfecte Pupple via onze app" en wellicht een kleinere slogan eronder met "Voor eenzame ouderen die een leuke middag verdienen".

**Comment by sharonvopzeeland** [comment]
Goeie!
