### ISSUE TITLE
Create API to retrieve Pupples from DB as JSON

### ISSUE THREAD

**Issue by MelvinIdema** [MelvinIdema/blok-tech-team#55]
- [x] Populate DB with Pupples
- [x] Create API
- [x] Retrieve API in front-end

**Comment by MelvinIdema** [comment]
@Bram-ter Laat jij weten als de pupples in de database staan? Desnoods alvast 2 ofzo

**Comment by MelvinIdema** [comment]
Kijk de API is letterlijk gewoon een route:
![Schermafbeelding 2022-03-29 om 14 43 53](https://user-images.githubusercontent.com/2219074/160613831-660a03bf-2497-4f93-b6e7-84f8db90f169.png)

En een hele kleine functie die alle Pupples uit de database als JSON stuurt:
![Schermafbeelding 2022-03-29 om 14 44 10](https://user-images.githubusercontent.com/2219074/160613892-1e955ddf-1414-4e1e-b35f-a5ee507e0ecf.png)

Pupple.find({}); is een functie die je krijgt vanuit Mongoose. De lege `{}` zegt: geef mij alle documenten maar. Geen filter.

En die kun je vervolgens zo ophalen:
![Schermafbeelding 2022-03-29 om 14 44 35](https://user-images.githubusercontent.com/2219074/160613959-b825f1dd-6ccb-4b7e-8485-caa4c315b116.png)

En dat is **precies** hetzelfde als zo'n random quote API:
![Schermafbeelding 2022-03-29 om 14 46 20](https://user-images.githubusercontent.com/2219074/160614277-a91d53bb-fc91-427a-9b72-e3f7e7ff7e93.png)

Dat bedoelde ik met *simpel* 😅  Dus je kunt ook precies dezelfde code gebruiken als in je frontend voor designers project. @danajamilla 

Hopelijk is het een beetje logisch en anders kijken we er donderdag nog wel ff naar. 👍🏼

**Comment by Bram-ter** [comment]
<img width="1031" alt="Screen Shot 2022-03-29 at 15 10 36" src="https://user-images.githubusercontent.com/94180118/160618744-e801f3b2-21c3-41e0-abaf-32afa412d6f2.png">
Heb dit tot nu toe, het lijkt alleen dat hij de lat en lon niet goed overzet vanuit de array @MelvinIdema

**Comment by sharonvopzeeland** [comment]
@Bram-ter Kan ik random een stad aan jouw lat / lon toevoegen in de database of moet ik een stad toevoegen die in de buurt is van jouw lat / lon ?

**Comment by sharonvopzeeland** [comment]
> @Bram-ter Kan ik random een stad aan jouw lat / lon toevoegen in de database of moet ik een stad toevoegen die in de buurt is van jouw lat / lon ?

& nu staat de beschrijving in het engels net als de personaliteit, niet netter als dit in nederlands is zoals de rest van de app?
